# Generated by Django 5.2.7 on 2025-10-23 13:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_logic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursaryapplication',
            name='cdf_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='chief_comments',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='chief_county',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='chief_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='chief_full_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='chief_location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='chief_signature_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='chief_sub_county',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='chief_sub_location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='county_gov_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='disability_nature',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='disability_reg_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='father_occupation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='fees_provider',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='guardian_relation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='has_disability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='inst_contact',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='inst_county',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='is_orphan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='is_single_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='ministry_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='mother_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='mother_occupation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='other_bursary_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='other_fees_provider',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='parent_declaration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='parent_id_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='parent_signature_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='student_declaration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='student_signature_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='term1_score',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='term2_score',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='term3_score',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sub_location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
