# Generated by Django 5.2.7 on 2025-10-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_logic', '0002_bursaryapplication_cdf_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationstatuslog',
            options={'verbose_name': 'Application Status Log', 'verbose_name_plural': 'Application Status Logs'},
        ),
        migrations.RemoveField(
            model_name='applicationstatuslog',
            name='changed_by',
        ),
        migrations.AlterField(
            model_name='applicationstatuslog',
            name='new_status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applicationstatuslog',
            name='old_status',
            field=models.CharField(max_length=50),
        ),
    ]
