# Generated by Django 5.2.7 on 2025-10-28 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_logic', '0003_alter_applicationstatuslog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationstatuslog',
            options={'ordering': ['-changed_at'], 'verbose_name': 'Application Status Log', 'verbose_name_plural': 'Application Status Logs'},
        ),
        migrations.RemoveIndex(
            model_name='bursaryapplication',
            name='idx_status',
        ),
        migrations.RemoveIndex(
            model_name='bursaryapplication',
            name='idx_created_at',
        ),
        migrations.RemoveIndex(
            model_name='bursaryapplication',
            name='idx_edu_level',
        ),
        migrations.AlterField(
            model_name='applicationstatuslog',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='bursaryapplication',
            name='application_number',
            field=models.CharField(db_index=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='bursaryapplication',
            name='education_level',
            field=models.CharField(choices=[('primary', 'Primary School'), ('secondary', 'Secondary School'), ('college', 'College'), ('university', 'University')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='bursaryapplication',
            name='family_status',
            field=models.CharField(choices=[('both_parents', 'Both Parents Alive'), ('single_parent', 'Single Parent'), ('orphan', 'Orphan'), ('guardian', 'Under Guardian')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='bursaryapplication',
            name='has_disability',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='bursaryapplication',
            name='institution_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bursaryapplication',
            name='is_orphan',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='bursaryapplication',
            name='is_single_parent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='bursaryapplication',
            name='previous_bursary_recipient',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='bursaryapplication',
            name='student_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bursaryapplication',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when application was first submitted'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('id_copy', 'ID Copy'), ('admission_letter', 'Admission Letter'), ('fee_structure', 'Fee Structure'), ('income_proof', 'Proof of Income'), ('parent_id', 'Parent/Guardian ID'), ('birth_certificate', 'Birth Certificate'), ('death_certificate', 'Death Certificate (if applicable)'), ('other', 'Other Document')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='county',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_number',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sub_county',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='applicationstatuslog',
            index=models.Index(fields=['application', '-changed_at'], name='idx_app_log'),
        ),
        migrations.AddIndex(
            model_name='bursaryapplication',
            index=models.Index(fields=['status', '-submitted_at'], name='idx_status_submitted'),
        ),
        migrations.AddIndex(
            model_name='bursaryapplication',
            index=models.Index(fields=['education_level', 'status'], name='idx_edu_status'),
        ),
        migrations.AddIndex(
            model_name='bursaryapplication',
            index=models.Index(fields=['user_profile', '-created_at'], name='idx_profile_created'),
        ),
        migrations.AddIndex(
            model_name='bursaryapplication',
            index=models.Index(fields=['is_orphan', 'status'], name='idx_orphan_status'),
        ),
        migrations.AddIndex(
            model_name='bursaryapplication',
            index=models.Index(fields=['has_disability', 'status'], name='idx_disability_status'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['application', 'document_type'], name='idx_app_doc_type'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['county', 'sub_county'], name='idx_location'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['id_number'], name='idx_id_number'),
        ),
    ]
