# Generated by Django 5.2.7 on 2025-10-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_logic', '0004_alter_applicationstatuslog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursaryapplication',
            name='flag_reason',
            field=models.TextField(blank=True, help_text='Reason why this application was flagged'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='is_flagged',
            field=models.BooleanField(db_index=True, default=False, help_text='Has this application been flagged for review?'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Has this application been verified by admin?'),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when application was verified', null=True),
        ),
        migrations.AddField(
            model_name='bursaryapplication',
            name='verified_by',
            field=models.CharField(blank=True, help_text='Username of admin who verified this application', max_length=150),
        ),
        migrations.AddField(
            model_name='document',
            name='is_flagged',
            field=models.BooleanField(default=False, verbose_name='Flagged for Review'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified (Pass)'), ('rejected', 'Rejected (Fail)')], default='pending', max_length=50, verbose_name='Verification Status'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_verified', 'is_flagged', 'status'], name='idx_verification'),
        ),
    ]
