# Generated by Django 5.2.7 on 2025-10-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_logic', '0005_bursaryapplication_flag_reason_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bursaryapplication',
            constraint=models.UniqueConstraint(fields=('user_profile',), name='unique_application_per_user'),
        ),
    ]
