name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10, 3.11]
    steps:
    - uses: actions/checkout@v4

    # FIX: Update to actions/setup-python@v5 for better compatibility
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5 
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        # Install Celery dependencies and testing dependencies
        pip install -r requirements.txt
        pip install coverage
    
    - name: Run Tests
      # Use coverage to run tests and generate a report
      run: |
        coverage run manage.py test
        coverage report
