name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10, 3.11]
    steps:
    - uses: actions/checkout@v4

    # FIX: Update to actions/setup-python@v5 for better compatibility
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5 
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        # Install Celery dependencies and testing dependencies
        pip install -r requirements.txt
        pip install coverage django-celery-results
    - name: Prepare Test Environment
      # If your settings.py tries to use PostgreSQL, this needs to be running.
      # If sticking to SQLite, this ensures the environment is clean.
      run: |
        echo "Creating log directory needed by settings.py"
        mkdir -p logs
        echo "Successfully prepared environment."
    
    - name: Run Tests
      # Use coverage to run tests and generate a report
      run: |
        echo "Starting Django tests..."
        # The test runner will automatically use the temporary test database (SQLite by default)
        coverage run --source='backend_logic' manage.py test backend_logic
    
    - name: Generate Coverage Report
      # Separate step for coverage report ensures results are visible even if tests fail
      run: |
        coverage report
